[phases.setup]
nixPkgs = ['bun']

[phases.install]
cmds = ['bun i --frozen-lockfile']

[phases.build]
cmds = ['bun install && bun build ./src/http/server.ts --outdir ./dist --target bun --entry-naming index.js']

[phases.start]
cmds = ['bun ./dist/index.js']